#!/bin/bash
set -e

for s in "$@"; do
	name="$(echo "$s/" | cut -f1 -d/)"
	pri="$(echo "$s/" | cut -f2 -d/)"
	if [ -z "$name" ]; then
		out="$out ENV_CREATE($pri);"
	elif [ -z "$pri" ]; then
		out="$out ENV_CREATE(test_$name);"
	else
		out="$out ENV_CREATE_PRIORITY(test_$name, $pri);"
	fi
done

# shellcheck disable=2028
echo 'void rv32_init(u_int hartid, u_int dtb) {
	printk("init.c:\trv32_init() is called\n");

	riscv_detect_memory(dtb);
	riscv_vm_init();
	page_init();
	env_init();

'"$out"'

	kclock_init();
	idt_init();
	while (1) {
	}
	panic("init.c:\tend of rv32_init() reached!");
}' > include/generated/init_override.h
